import smtplib, ssl
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import time
from datetime import date

def send_email(receiver_email, route='https://www.google.com/'):
  today = str(date.today())
  today = today[5:]
  months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
  today = months[int(today[:2]) - 1] + ' ' + today[3:]

  t = time.localtime()
  current_time = time.strftime("%H:%M", t)

  if len(current_time) > 4:
    current_time = str(int(current_time[:2]) - 12) + ':' + current_time[3:] + ' PM'
  else:
    current_time = current_time + ' AM'

  timestamp = today + ' ' + current_time
  sender_email = "autorouting.app"
  password = '________' #Fill in the password
  message = MIMEMultipart("alternative")
  message["Subject"] = 'Your Route Has Generated, ' + timestamp 
  message["From"] = sender_email
  message["To"] = receiver_email

  html1 = """\
  <html>
    <body>
      <p>Hi,<br>
        Your route is: <a href="
  """
  html2 =         """
  "><b>Here</b></a><br><br><br>
       <i>Generated by the Autorouting Application at: <a href="http://www.techworldconnect.com/delivery/">http://www.techworldconnect.com/delivery/</a> <br>
       -The Autorouting Team</i>
    </p>
  </body>
</html>
"""
  html = html1 + str(route) + html2
  content = MIMEText(html, "html")


  message.attach(content)


  context = ssl.create_default_context()
  with smtplib.SMTP_SSL("smtp.gmail.com", 465, context=context) as server:
    server.login(sender_email, password)
    server.sendmail(
        sender_email, receiver_email, message.as_string()
    )

send_email('jaden.mu@gmail.com')
print(1)